alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_CULTMET foreign key (ID_CULTMET_ID) references INVCULT_CULTMET(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_CULTMET on INVCULT_INVENTORY (ID_CULTMET_ID);
