alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_CROPS foreign key (ID_CROPS_ID) references INVCULT_CROPS(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_CROPS on INVCULT_INVENTORY (ID_CROPS_ID);
