alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_LOCFERMA foreign key (ID_LOCFERMA_ID) references INVCULT_LOCATION(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_LOCFERMA on INVCULT_INVENTORY (ID_LOCFERMA_ID);
