alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_SYSAGR foreign key (ID_SYSAGR_ID) references INVCULT_SYSAGR(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_SYSAGR on INVCULT_INVENTORY (ID_SYSAGR_ID);
