alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_STORPLACE foreign key (ID_STORPLACE_ID) references INVCULT_STORPLACE(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_STORPLACE on INVCULT_INVENTORY (ID_STORPLACE_ID);
