alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_LOCINV foreign key (ID_LOCINV_ID) references INVCULT_LOCALITYSIRUTA(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_LOCINV on INVCULT_INVENTORY (ID_LOCINV_ID);
