alter table INVCULT_WORKDIVISION add constraint FK_INVCULT_WORKDIVISION_ON_INVENTORY foreign key (INVENTORY_ID) references INVCULT_INVENTORY(ID);
create index IDX_INVCULT_WORKDIVISION_ON_INVENTORY on INVCULT_WORKDIVISION (INVENTORY_ID);
