alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_OLDVAR foreign key (ID_OLDVAR_ID) references INVCULT_OLDVAR(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_OLDVAR on INVCULT_INVENTORY (ID_OLDVAR_ID);
