alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_DRYPLACE foreign key (ID_DRYPLACE_ID) references INVCULT_DRYPLACE(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_DRYPLACE on INVCULT_INVENTORY (ID_DRYPLACE_ID);
