alter table INVCULT_LOCATION add constraint FK_INVCULT_LOCATION_ON_ID_MANDATAR foreign key (ID_MANDATAR_ID) references INVCULT_FARMERS(ID);
create index IDX_INVCULT_LOCATION_ON_ID_MANDATAR on INVCULT_LOCATION (ID_MANDATAR_ID);
