create unique index IDX_INVCULT_ZONESIRUTA_UK_ZONENUMBER on INVCULT_ZONESIRUTA (ZONENUMBER) where DELETE_TS is null ;
create unique index IDX_INVCULT_ZONESIRUTA_UK_ZONENAME on INVCULT_ZONESIRUTA (ZONENAME) where DELETE_TS is null ;
create unique index IDX_INVCULT_ZONESIRUTA_UK_SIRUTA on INVCULT_ZONESIRUTA (SIRUTA) where DELETE_TS is null ;
