alter table INVCULT_FARMERS add constraint FK_INVCULT_FARMERS_ON_ID_TIPPERSOANA foreign key (ID_TIPPERSOANA_ID) references INVCULT_TIPPERSOANA(ID);
create index IDX_INVCULT_FARMERS_ON_ID_TIPPERSOANA on INVCULT_FARMERS (ID_TIPPERSOANA_ID);
