alter table INVCULT_LOCALITYSIRUTA add constraint FK_INVCULT_LOCALITYSIRUTA_ON_ID_COUNTYSIRUTA foreign key (ID_COUNTYSIRUTA_ID) references INVCULT_COUNTYSIRUTA(ID);
create unique index IDX_INVCULT_LOCALITYSIRUTA_UK_SIRUTA on INVCULT_LOCALITYSIRUTA (SIRUTA) where DELETE_TS is null ;
create index IDX_INVCULT_LOCALITYSIRUTA_ON_ID_COUNTYSIRUTA on INVCULT_LOCALITYSIRUTA (ID_COUNTYSIRUTA_ID);
