alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_PERSONS foreign key (ID_PERSONS_ID) references INVCULT_PERSONS(ID);
alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_LOCINV foreign key (LOCINV_ID) references INVCULT_LOCALITYSIRUTA(ID);
alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_ID_FARMERS foreign key (ID_FARMERS_ID) references INVCULT_FARMERS(ID);
alter table INVCULT_INVENTORY add constraint FK_INVCULT_INVENTORY_ON_LOCFERMA foreign key (LOCFERMA_ID) references INVCULT_LOCATION(ID);
create index IDX_INVCULT_INVENTORY_ON_ID_PERSONS on INVCULT_INVENTORY (ID_PERSONS_ID);
create index IDX_INVCULT_INVENTORY_ON_LOCINV on INVCULT_INVENTORY (LOCINV_ID);
create index IDX_INVCULT_INVENTORY_ON_ID_FARMERS on INVCULT_INVENTORY (ID_FARMERS_ID);
create index IDX_INVCULT_INVENTORY_ON_LOCFERMA on INVCULT_INVENTORY (LOCFERMA_ID);
