-- begin INVCULT_ZONESIRUTA
create unique index IDX_INVCULT_ZONESIRUTA_UK_ZONENUMBER on INVCULT_ZONESIRUTA (ZONENUMBER) where DELETE_TS is null ^
create unique index IDX_INVCULT_ZONESIRUTA_UK_ZONENAME on INVCULT_ZONESIRUTA (ZONENAME) where DELETE_TS is null ^
create unique index IDX_INVCULT_ZONESIRUTA_UK_SIRUTA on INVCULT_ZONESIRUTA (SIRUTA) where DELETE_TS is null ^
-- end INVCULT_ZONESIRUTA
-- begin INVCULT_LOCALITYSIRUTA
alter table INVCULT_LOCALITYSIRUTA add constraint FK_INVCULT_LOCALITYSIRUTA_ON_ID_COUNTYSIRUTA foreign key (ID_COUNTYSIRUTA_ID) references INVCULT_COUNTYSIRUTA(ID)^
create unique index IDX_INVCULT_LOCALITYSIRUTA_UK_SIRUTA on INVCULT_LOCALITYSIRUTA (SIRUTA) where DELETE_TS is null ^
create index IDX_INVCULT_LOCALITYSIRUTA_ON_ID_COUNTYSIRUTA on INVCULT_LOCALITYSIRUTA (ID_COUNTYSIRUTA_ID)^
-- end INVCULT_LOCALITYSIRUTA
-- begin INVCULT_COUNTYSIRUTA
alter table INVCULT_COUNTYSIRUTA add constraint FK_INVCULT_COUNTYSIRUTA_ON_ID_ZONESIRUTA foreign key (ID_ZONESIRUTA_ID) references INVCULT_ZONESIRUTA(ID)^
create unique index IDX_INVCULT_COUNTYSIRUTA_UK_MNEMONIC on INVCULT_COUNTYSIRUTA (MNEMONIC) where DELETE_TS is null ^
create unique index IDX_INVCULT_COUNTYSIRUTA_UK_SIRUTA on INVCULT_COUNTYSIRUTA (SIRUTA) where DELETE_TS is null ^
create unique index IDX_INVCULT_COUNTYSIRUTA_UK_CODE on INVCULT_COUNTYSIRUTA (CODE) where DELETE_TS is null ^
create unique index IDX_INVCULT_COUNTYSIRUTA_UK_NAME on INVCULT_COUNTYSIRUTA (NAME) where DELETE_TS is null ^
create index IDX_INVCULT_COUNTYSIRUTA_ON_ID_ZONESIRUTA on INVCULT_COUNTYSIRUTA (ID_ZONESIRUTA_ID)^
-- end INVCULT_COUNTYSIRUTA
-- begin INVCULT_FARMERS
alter table INVCULT_FARMERS add constraint FK_INVCULT_FARMERS_ON_ID_TIPPERSOANA foreign key (ID_TIPPERSOANA_ID) references INVCULT_TIPPERSOANA(ID)^
create index IDX_INVCULT_FARMERS_ON_ID_TIPPERSOANA on INVCULT_FARMERS (ID_TIPPERSOANA_ID)^
-- end INVCULT_FARMERS
